package core_order

var (
	ORDER_STATUS_SUCCESS             = "SUCCESS"
	ORDER_STATUS_TIMEOUT             = "TIMEOUT"
	ORDER_STATUS_WAITING_FOR_PAYMENT = "WAITING_FOR_PAYMENT"
	ORDER_STATUS_CANCELED            = "CANCELED"
)
